// Typed manifest of every processed media asset in public/media/.
// Generated by scripts/prepare-media.mjs from assets-raw/ (gitignored originals).
// Visual components must import paths from here — never hardcode a /media/... string.
// See .superpowers/sdd/2026-08-03-spiderman-bnd/task-2-report.md for sourcing details.

export const MEDIA = {
  maskEye: "/media/mask-eye.jpg",
  maskEyeNormal: "/media/mask-eye-normal.png",
  poster: "/media/poster.webp",
  spidey: "/media/spidey.webp",
  nyc: ["/media/nyc-1.webp", "/media/nyc-2.webp", "/media/nyc-3.webp", "/media/nyc-4.webp", "/media/nyc-5.webp"],
  villains: { scorpion: "/media/villain-scorpion.webp", tombstone: "/media/villain-tombstone.webp", unseen: "/media/poster.webp" },
  wildcards: { punisher: "/media/punisher.webp", hulk: "/media/hulk.webp" },
  gallery: ["/media/still-1.webp", "/media/still-2.webp", "/media/still-3.webp", "/media/still-4.webp", "/media/still-5.webp", "/media/still-6.webp"],
  timeline: ["/media/timeline-homecoming.webp", "/media/timeline-ffh.webp", "/media/timeline-nwh.webp", "/media/timeline-bnd.webp"],
} as const;

// Official "SPIDER-MAN: BRAND NEW DAY – Official Trailer (HD)", published on the
// verified Sony/Marvel "Spider-Man" YouTube channel (youtube.com/@spiderman).
export const TRAILER_YT_ID = "8TZMtslA3UY";
